# bakend deployment
kind: Deployment
apiVersion: apps/v1

metadata:
  name: bakend_deployment
  namespace: founderhq_ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: founderhq_bakend
  template:
    metadata:
      labels:
        app: founderhq_bakend

    spec:
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
      initContainers:
        - name: wait_for_backend
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "until nc -z mongodb_service 27017;do echo waiting for mongodb ;sleep 2;done;",
            ]

        - name: create_logs_folder
          image: busybox:latest
          command: ["sh", "-c", "mkdir backend_logs"]

      containers:
        - name: bakend_container
          image: bakend:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: backend_logs
              mountPath: /logs

        - name: log_finder
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "while true; do cp /logs/* backend_logs/; sleep 3;done",
            ]
          volumeMounts:
            - name: backend_logs
              mountPath: /logs

      volumes:
        - name: backend_logs
          persistentVolumeClaim:
            claimName: backend_pvc

---
# bakend Serviv mainfiest

kind: Service
apiVersion: v1

metadata:
  name: bakend_service
  namespace: founderhq_ns
spec:
  type: ClusterIP
  selector:
    app: founderhq_bakend
  ports:
    - port: 8000
      targetPort: 8000
