apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: founderhq-ns
type: Opaque
data:
  # Values are base64 encoded without trailing newlines
  MONGO_INITDB_ROOT_USERNAME: Z291cmF2
  MONGO_INITDB_ROOT_PASSWORD: Zm91bmRlcmhx
