apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: founderhq-ns
type: Opaque
data:
  # Values are base64 encoded
  MONGO_INITDB_ROOT_USERNAME: Z291cmF2Cg==
  MONGO_INITDB_ROOT_PASSWORD: Zm91bmRlcmhxCg==
