apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /mnt/c/Users/Acer/Desktop/test/databinding/backend

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: huddle-backend-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /mnt/c/Users/Acer/Desktop/test/databinding/huddle

---
# PVC for Backend Logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: founderhq-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---
# PVC for Huddle Backend Logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huddle-backend-pvc
  namespace: founderhq-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
