apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: founderhq-application
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.email: gouravbirwaz@gmail.com

spec:
  project: default

  source:
    repoURL: https://github.com/Gouravbirwaz/FounderHq.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: founderhq-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true